version: '3.7'
services:
  web:
    image: nginx:alpine
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/share/nginx/html
networks:
  default:
    external:
      name: test-bridge-network       